title: Buzyka's tech blog
description: "tech stuff that is worth sharing"
author:
  name: "Ivan Buzyka"
  url: "https://buzyka.de"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/
timezone: UTC

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: jekyll-theme-slate
future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
